meta_product_name: "SRD kartotéky"
meta_title: "SRD kartotéky - snadné vyhledávání v RPG zdrojích"
meta_description: "Vyhledejte kouzla, předměty, triky, monstra a další snadno a jednoduše."
meta_image: "cover.png"
twitter_account: "@d20vkostce"
